In [0]:
#Author: Yuanzong Zhang, Jun Zhang#
import numpy as np
import pandas as pd
from sklearn import preprocessing
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
from keras.models import Model

In [0]:
#!/usr/bin/env Python
# coding=utf-8

df = pd.read_csv('Data_tai_lake.csv')
df.head()

pH     TN     TP  Chlorophy  DeMgChlorophy  Permanganate      AN     NN  \
0  7.70  10.23  0.430       5.00           3.31          8.73   2.854  0.156   
1  7.76   7.32  0.583       9.29           1.68          5.18   3.692  0.110   
2  7.79  12.74  0.493      19.15           8.88          9.89  10.010  0.161   
3  7.68  10.80  0.350      37.75          10.78          9.71   4.071  0.166   
4  7.65  11.20  0.323      96.42          21.90          9.53   3.864  0.279   

   Ni-nitr  DissolvedN        ...         alkalinity    PI    SI    CI     MI  \
0    2.279         NaN        ...               2.79  7.16  55.1  42.1  11.44   
1    2.021         NaN        ...               2.41  5.60  42.0  36.3   9.48   
2    2.399         NaN        ...               3.35  7.90  91.6  36.4  12.86   
3    2.420         NaN        ...               2.88  4.85  70.2  28.6   8.64   
4    4.021         NaN        ...               2.50  5.22  54.4  39.5   8.59   

      FI    Col     Sul    Sil  dissolved-oxygen  
0  0.613  68.42   94.10  179.2              2.50  
1  0.601  55.79   81.62  121.3              9.49  
2  0.375  88.90  107.76  151.0              1.58  
3  0.547  73.60  112.00   91.8              3.06  
4  0.640  60.60   96.10  106.5              2.11  

[5 rows x 22 columns]

In [0]:
print ('Variance of DO: ', df['dissolved-oxygen'].var())
print ('Mean of DO: ', df['dissolved-oxygen'].mean())

Variance of DO:  7.981873193758521
Mean of DO:  8.182543554006969


In [0]:
df = df.fillna(df.mean())
df

pH     TN     TP  Chlorophy  DeMgChlorophy  Permanganate      AN  \
0    7.70  10.23  0.430       5.00           3.31          8.73   2.854   
1    7.76   7.32  0.583       9.29           1.68          5.18   3.692   
2    7.79  12.74  0.493      19.15           8.88          9.89  10.010   
3    7.68  10.80  0.350      37.75          10.78          9.71   4.071   
4    7.65  11.20  0.323      96.42          21.90          9.53   3.864   
5    7.40   9.34  0.223      26.08           4.67          7.04   3.101   
6    7.78   5.71  0.328      35.51           4.13          7.07   3.460   
7    7.70   3.06  0.175      62.85          18.95          7.41   0.535   
8    8.15   1.04  0.182      46.10           3.50          5.87   0.034   
9    7.70   7.47  0.288      13.30           5.90          6.29   5.288   
10   7.87  10.20  0.278      14.23           6.28          6.81   7.524   
11   7.60   8.93  0.306       2.14           7.86          7.98   5.400   
12   7.67  10.89  0.361       9.11           6.30          7.58   7.329   
13   7.39   9.75  0.604       6.78           6.40          9.11   7.935   
14   7.68  11.34  0.383      13.57           7.93          8.77   9.009   
15   7.95   9.99  0.333      43.83          16.60          8.65   6.096   
16   7.40   7.41  0.268      19.59           9.87          6.34   3.474   
17   8.67   5.33  0.426      85.07          17.79          8.25   1.866   
18   7.59   8.07  0.381      90.02          33.69          8.99   3.989   
19   8.00   5.77  0.273      15.02           9.66          5.66   4.176   
20   7.75   5.79  0.295      16.52           6.61          5.04   3.939   
21   7.95   7.36  0.268      62.94          19.12          7.79   2.366   
22   7.97   8.96  0.234      15.96           5.37          6.89   5.757   
23   8.09   7.80  0.149       9.64           4.42          6.46   5.025   
24   8.31   5.58  0.114      14.28           3.21          6.21   2.450   
25   7.78  12.75  0.271      10.45           4.74          8.65   7.032   
26   7.78  12.50  0.562       4.05           3.88          9.72   8.049   
27   7.95   7.46  0.147      39.92           5.70          7.05   2.700   
28   7.81   9.21  0.219      25.00           5.62          6.79   6.984   
29   7.54   7.45  0.237      11.65           1.26          5.54   4.660   
..    ...    ...    ...        ...            ...           ...     ...   
546  8.09   2.85  0.049      10.04           4.02          3.06   0.040   
547  8.35   1.70  0.061      14.84           3.20          3.61   0.040   
548  8.16   2.18  0.161      33.85           2.60          5.96   0.060   
549  8.46   1.20  0.070       9.82           2.68          5.13   0.070   
550  8.17   1.26  0.071       8.93           2.32          3.97   0.050   
551  8.27   2.17  0.073      31.25           9.37          4.81   0.030   
552  8.12   5.07  0.124       5.86           1.25          5.56   1.060   
553  7.99   2.97  0.109       3.12           0.70          4.60   0.620   
554  8.18   2.80  0.104       1.79           1.34          4.27   0.340   
555  8.46   4.00  0.087       7.14           4.11          4.15   0.040   
556  8.07   3.82  0.080       9.82           7.68          4.08   0.060   
557  8.35   3.00  0.054      11.61           2.14          4.71   0.050   
558  8.20   2.64  0.042       8.93           6.70          3.03   0.030   
559  8.04   2.18  0.130      13.28           2.58          3.52   0.050   
560  8.16   2.75  0.141      66.96           1.39          5.39   0.050   
561  8.21   1.45  0.063       6.25           0.62          2.77   0.210   
562  8.14   1.43  0.065       4.69           4.61          2.69   0.090   
563  7.95   3.91  0.200      11.61           3.39          5.04   0.210   
564  7.98   2.13  0.111       5.39           2.78          4.47   0.120   
565  7.99   8.09  0.157       5.36           1.52          5.49   3.260   
566  8.02   6.37  0.127      11.61           2.14          4.92   1.090   
567  8.07   4.54  0.088       2.

In [0]:
x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_scaled = pd.DataFrame(x_scaled)
df_scaled

0         1         2         3         4         5         6   \
0    0.326271  0.747153  0.192125  0.009584  0.057039  0.419153  0.284901   
1    0.351695  0.526196  0.264706  0.017806  0.028951  0.172797  0.368642   
2    0.364407  0.937737  0.222011  0.036705  0.153024  0.499653  1.000000   
3    0.317797  0.790433  0.154175  0.072355  0.185766  0.487162  0.406515   
4    0.305085  0.820805  0.141366  0.184808  0.377391  0.474670  0.385830   
5    0.199153  0.679575  0.093928  0.049988  0.080476  0.301874  0.309583   
6    0.360169  0.403948  0.143738  0.068062  0.071170  0.303956  0.345458   
7    0.326271  0.202733  0.071157  0.120465  0.326555  0.327550  0.053163   
8    0.516949  0.049355  0.074478  0.088360  0.060314  0.220680  0.003098   
9    0.326271  0.537585  0.124763  0.025492  0.101672  0.249827  0.528130   
10   0.398305  0.744875  0.120019  0.027275  0.108220  0.285913  0.751574   
11   0.283898  0.648443  0.133302  0.004102  0.135447  0.367106  0.539322   
12   0.313559  0.797267  0.159393  0.017461  0.108565  0.339348  0.732088   
13   0.194915  0.710706  0.274668  0.012995  0.110288  0.445524  0.792645   
14   0.317797  0.831435  0.169829  0.026010  0.136653  0.421929  0.899970   
15   0.432203  0.728929  0.146110  0.084009  0.286059  0.413602  0.608874   
16   0.199153  0.533030  0.115275  0.037548  0.170084  0.253296  0.346857   
17   0.737288  0.375095  0.190228  0.163054  0.306566  0.385843  0.186170   
18   0.279661  0.583144  0.168880  0.172541  0.580562  0.437196  0.398321   
19   0.453390  0.408504  0.117647  0.028789  0.166466  0.206107  0.417008   
20   0.347458  0.410023  0.128083  0.031664  0.113907  0.163081  0.393325   
21   0.432203  0.529233  0.115275  0.120637  0.329485  0.353921  0.236135   
22   0.440678  0.650721  0.099146  0.030591  0.092538  0.291464  0.574998   
23   0.491525  0.562642  0.058824  0.018477  0.076167  0.261624  0.501849   
24   0.584746  0.394077  0.042220  0.027370  0.055316  0.244275  0.244529   
25   0.360169  0.938497  0.116698  0.020030  0.081682  0.413602  0.702408   
26   0.360169  0.919514  0.254744  0.007763  0.066862  0.487856  0.804037   
27   0.432203  0.536826  0.057875  0.076515  0.098225  0.302568  0.269511   
28   0.372881  0.669704  0.092030  0.047918  0.096846  0.284525  0.697612   
29   0.258475  0.536067  0.100569  0.022330  0.021713  0.197779  0.465374   
..        ...       ...       ...       ...       ...       ...       ...   
546  0.491525  0.186788  0.011385  0.019244  0.069275  0.025677  0.003697   
547  0.601695  0.099468  0.017078  0.028444  0.055144  0.063845  0.003697   
548  0.521186  0.135915  0.064516  0.064880  0.044804  0.226926  0.005696   
549  0.648305  0.061503  0.021347  0.018822  0.046183  0.169327  0.006695   
550  0.525424  0.066059  0.021822  0.017116  0.039979  0.088827  0.004697   
551  0.567797  0.135156  0.022770  0.059897  0.161468  0.147120  0.002698   
552  0.504237  0.355353  0.046964  0.011232  0.021541  0.199167  0.105626   
553  0.449153  0.195900  0.039848  0.005980  0.012063  0.132547  0.061657   
554  0.529661  0.182992  0.037476  0.003431  0.023092  0.109646  0.033676   
555  0.648305  0.274108  0.029412  0.013685  0.070825  0.101319  0.003697   
556  0.483051  0.260440  0.026091  0.018822  0.132345  0.096461  0.005696   
557  0.601695  0.198178  0.013757  0.022253  0.036877  0.140180  0.004697   
558  0.538136  0.170843  0.008065  0.017116  0.115458  0.023595  0.002698   
559  0.470339  0.135915  0.049810  0.025454  0.044460  0.057599  0.004697   
560  0.521186  0.179195  0.055028  0.128342  0.023953  0.187370  0.004697   
561  0.542373  0.080486  0.018027  0.011979  0.010684  0.005552  0.020686   
562  0.512712  0.078967  0.018975  0.008989  0.079442  0.000000  0.008694   
563  0.432203  0.267274  0.083017  0.022253  0.058418  0.163081  0.020686   
564  0.444915  0.132118  0.040797  0.010331  0.047906  0.123525  0.011692   
565  0.449153  0.584662  0.062619  0.010274  0.026193  0.194310  0.325472   
566  0.

In [0]:
x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_scaled = pd.DataFrame(x_scaled)
df_scaled

0         1         2         3         4         5         6   \
0    0.326271  0.747153  0.192125  0.419153  0.284901  0.022305  0.532367   
1    0.351695  0.526196  0.264706  0.172797  0.368642  0.015686  0.472073   
2    0.364407  0.937737  0.222011  0.499653  1.000000  0.023025  0.560411   
3    0.317797  0.790433  0.154175  0.487162  0.406515  0.023744  0.565319   
4    0.305085  0.820805  0.141366  0.474670  0.385830  0.040006  0.939472   
5    0.199153  0.679575  0.093928  0.301874  0.309583  0.025471  1.000000   
6    0.360169  0.403948  0.143738  0.303956  0.345458  0.026335  0.164291   
7    0.326271  0.202733  0.071157  0.327550  0.053163  0.038279  0.196775   
8    0.516949  0.049355  0.074478  0.220680  0.003098  0.001871  0.008179   
9    0.326271  0.537585  0.124763  0.249827  0.528130  0.021010  0.125964   
10   0.398305  0.744875  0.120019  0.285913  0.751574  0.028637  0.148633   
11   0.283898  0.648443  0.133302  0.367106  0.539322  0.026335  0.299603   
12   0.313559  0.797267  0.159393  0.339348  0.732088  0.016837  0.248656   
13   0.194915  0.710706  0.274668  0.445524  0.792645  0.003022  0.042300   
14   0.317797  0.831435  0.169829  0.421929  0.899970  0.034681  0.294695   
15   0.432203  0.728929  0.146110  0.413602  0.608874  0.023313  0.220379   
16   0.199153  0.533030  0.115275  0.253296  0.346857  0.028205  0.707642   
17   0.737288  0.375095  0.190228  0.385843  0.186170  0.019139  0.132040   
18   0.279661  0.583144  0.168880  0.437196  0.398321  0.034825  0.227857   
19   0.453390  0.408504  0.117647  0.206107  0.417008  0.023744  0.204020   
20   0.347458  0.410023  0.128083  0.163081  0.393325  0.019715  0.273428   
21   0.432203  0.529233  0.115275  0.353921  0.236135  0.019139  0.394017   
22   0.440678  0.650721  0.099146  0.291464  0.574998  0.022737  0.400561   
23   0.491525  0.562642  0.058824  0.261624  0.501849  0.010217  0.263847   
24   0.584746  0.394077  0.042220  0.244275  0.244529  0.005756  0.279738   
25   0.360169  0.938497  0.116698  0.413602  0.702408  0.022737  0.129703   
26   0.360169  0.919514  0.254744  0.487856  0.804037  0.028925  0.286516   
27   0.432203  0.536826  0.057875  0.302568  0.269511  0.023601  0.426969   
28   0.372881  0.669704  0.092030  0.284525  0.697612  0.046482  0.028278   
29   0.258475  0.536067  0.100569  0.197779  0.465374  0.024176  0.131806   
..        ...       ...       ...       ...       ...       ...       ...   
546  0.491525  0.186788  0.011385  0.025677  0.003697  0.000863  0.369011   
547  0.601695  0.099468  0.017078  0.063845  0.003697  0.000288  0.180416   
548  0.521186  0.135915  0.064516  0.226926  0.005696  0.000288  0.014723   
549  0.648305  0.061503  0.021347  0.169327  0.006695  0.000288  0.014723   
550  0.525424  0.066059  0.021822  0.088827  0.004697  0.000144  0.035756   
551  0.567797  0.135156  0.022770  0.147120  0.002698  0.000576  0.176209   
552  0.504237  0.355353  0.046964  0.199167  0.105626  0.003598  0.293994   
553  0.449153  0.195900  0.039848  0.132547  0.061657  0.001439  0.173639   
554  0.529661  0.182992  0.037476  0.109646  0.033676  0.001871  0.199346   
555  0.648305  0.274108  0.029412  0.101319  0.003697  0.000288  0.436784   
556  0.483051  0.260440  0.026091  0.096461  0.005696  0.000720  0.493340   
557  0.601695  0.198178  0.013757  0.140180  0.004697  0.000576  0.239308   
558  0.538136  0.170843  0.008065  0.023595  0.002698  0.000432  0.264080   
559  0.470339  0.135915  0.049810  0.057599  0.004697  0.000432  0.088806   
560  0.521186  0.179195  0.055028  0.187370  0.004697  0.000720  0.043702   
561  0.542373  0.080486  0.018027  0.005552  0.020686  0.000576  0.081795   
562  0.512712  0.078967  0.018975  0.000000  0.008694  0.000000  0.059593   
563  0.432203  0.267274  0.083017  0.163081  0.020686  0.001295  0.184389   
564  0.444915  0.132118  0.040797  0.123525  0.011692  0.000432  0.095583   
565  0.449153  0.584662  0.062619  0.194310  0.325472  0.005612  0.429773   
566  0.

In [0]:
# Feature engineering function to define time series data
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [0]:
# Small Lstms for forcasting the features in the target timeline.
step_size = 3
y_predict = []
n_features = 1

for indx in df_scaled.columns:
    X, y = split_sequence(df_scaled[indx], step_size)
#     print (X.shape)
    X_train = X[0:X.shape[0], :]
    y_train = y[0:X.shape[0]]
    X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], n_features))
    # define model
    model = Sequential()
    model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(step_size, n_features)))
#     model.add(LSTM(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    # fit model
    model.fit(X_train, y_train, epochs=200, verbose=0)
    # demonstrate prediction
    x_input = X_train[-1]
    x_input = x_input.reshape((1, step_size, n_features))
    yhat = model.predict(x_input, verbose=0)
    y_predict.append(yhat)
    print (x_input)
    print (yhat)
print (y_predict)
# 0.542373	0.148823	0.036053	0.012171	0.002585	0.176960	0.015689	0.005756	0.149334	0.112283

[[[0.49152542]
  [0.59322034]
  [0.56355932]]]
[[0.5629217]]
[[[0.08883827]
  [0.06909643]
  [0.07289294]]]
[[0.11308458]]
[[[0.04127135]
  [0.02609108]
  [0.03462998]]]
[[0.03762695]]
[[[0.01924367]
  [0.00854848]
  [0.00642095]]]
[[0.01817152]]
[[[0.00189557]
  [0.00930553]
  [0.0230915 ]]]
[[0.03560275]]
[[[0.20680083]
  [0.15336572]
  [0.13046495]]]
[[0.15018675]]
[[[0.00469671]
  [0.00469671]
  [0.00469671]]]
[[0.01932146]]
[[[0.00143906]
  [0.00057562]
  [0.00028781]]]
[[0.00346873]]
[[[0.02547324]
  [0.06753914]
  [0.03715821]]]
[[0.11575716]]
[[[0.04295403]
  [0.03165034]
  [0.03240392]]]
[[0.08427291]]
[[[9.70873786e-05]
  [7.76699029e-04]
  [9.70873786e-05]]]
[[0.00188988]]
[[[0.12809917]
  [0.06198347]
  [0.02066116]]]
[[0.07205319]]
[[[0.46180019]
  [0.486545  ]
  [0.52366223]]]
[[0.54490244]]
[[[0.54710921]
  [0.53747323]
  [0.55246253]]]
[[0.510298]]
[[[0.42674617]
  [0.44122658]
  [0.4548552 ]]]
[[0.44401395]]
[[[0.11538462]
  [0.22564103]
  [0.16923077]]]
[[0.36638293]]

In [0]:
# use middle variable to substitute y_predict in case missing the important values
a = y_predict
a

[array([[0.5629217]], dtype=float32),
 array([[0.11308458]], dtype=float32),
 array([[0.03762695]], dtype=float32),
 array([[0.01817152]], dtype=float32),
 array([[0.03560275]], dtype=float32),
 array([[0.15018675]], dtype=float32),
 array([[0.01932146]], dtype=float32),
 array([[0.00346873]], dtype=float32),
 array([[0.11575716]], dtype=float32),
 array([[0.08427291]], dtype=float32),
 array([[0.00188988]], dtype=float32),
 array([[0.07205319]], dtype=float32),
 array([[0.54490244]], dtype=float32),
 array([[0.510298]], dtype=float32),
 array([[0.44401395]], dtype=float32),
 array([[0.36638293]], dtype=float32),
 array([[0.15633306]], dtype=float32),
 array([[0.05444932]], dtype=float32),
 array([[0.51104784]], dtype=float32),
 array([[0.34316665]], dtype=float32),
 array([[0.58266425]], dtype=float32),
 array([[0.60298973]], dtype=float32)]

In [0]:
y_predict_clean = []
for i in a:
    y_predict_clean.append(i[0])
y_predict_clean = np.array(y_predict_clean)
y_predict_clean = y_predict_clean[0:21]

X_last = df_scaled.values[-1]
X_last_scaled_real = X_last[0:21]
y_last_scaled_real = X_last[-1]
relative_error = ((y_predict_clean.T - (X_last_scaled_real))/X_last_scaled_real)
print (relative_error*100)

In [0]:
X = df_scaled.values
print (X.shape)
X_train = X[0:X.shape[0]-1,0:X.shape[1]-1]
y_train = X[0:X.shape[0]-1,-1]
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
# y = y.reshape(y.shape[0], 1, y.shape[1])
print (X_train.shape)
print (y_train.shape)

(576, 19)
(575, 1, 18)
(575,)


In [0]:
# model = Sequential()
# mymodel = model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(X_train.shape[1], X_train.shape[2])))

In [0]:
#building bd-lstm on forecasting the target OD
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(X_train.shape[1], X_train.shape[2])))
# model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
# model.add(LSTM(50, activation='relu'))
# model.add(LSTM(50, input_shape = (X_train.shape[1], X_train.shape[2])))
model.add(Dense(1))
model.compile(loss='mae', optimizer='adam')
# fit network
model.fit(X_train, y_train, epochs=200, verbose=0)
# history = model.fit(train_X, train_y, epochs=50, batch_size=72, validation_data=(test_X, test_y), verbose=2, shuffle=False)

In [0]:
y_predict_clean = np.array([np.delete(y_predict_clean, [3,4,10])])

In [0]:
X_test = (y_predict_clean)
print (X_test.shape)
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
print (X_test.shape)
y_test = model.predict(X_test, verbose=0)

(1, 18)
(1, 1, 18)


In [0]:
# Calculate the value we predicted with the real value, get the relative error
relative_error = (y_test - y_last_scaled_real)/y_last_scaled_real
print (y_test)
print (y_last_scaled_real)
print ('Relative error: ', abs(relative_error*100))

[[0.62124795]]
0.7238962859145059
Relative error:  [[14.179976]]


In [0]:
# [array([[0.5629217]], dtype=float32),
#  array([[0.11308458]], dtype=float32),
#  array([[0.03762695]], dtype=float32),
#  array([[0.01817152]], dtype=float32),
#  array([[0.03560275]], dtype=float32),
#  array([[0.15018675]], dtype=float32),
#  array([[0.01932146]], dtype=float32),
#  array([[0.00346873]], dtype=float32),
#  array([[0.11575716]], dtype=float32),
#  array([[0.08427291]], dtype=float32),
#  array([[0.00188988]], dtype=float32),
#  array([[0.07205319]], dtype=float32),
#  array([[0.54490244]], dtype=float32),
#  array([[0.510298]], dtype=float32),
#  array([[0.44401395]], dtype=float32),
#  array([[0.36638293]], dtype=float32),
#  array([[0.15633306]], dtype=float32),
#  array([[0.05444932]], dtype=float32),
#  array([[0.51104784]], dtype=float32),
#  array([[0.34316665]], dtype=float32),
#  array([[0.58266425]], dtype=float32),
#  array([[0.60298973]], dtype=float32)]